version: "3.9"

services:
  backend:
    image: quarkus/s3-mvp-backend
    build:
      context: ../s3-mvp-backend
      dockerfile: Dockerfile
    container_name: s3-backend
    ports:
      - "8080:8080"
    networks:
      - s3-net

  frontend:
    image: s3-mvp-frontend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: s3-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - s3-net

networks:
  s3-net:
    driver: bridge
