version: "3.9"

services:
  backend:
    image: s3-mvp-backend
    container_name: s3-backend
    ports:
      - "8080:8080"
    networks:
      - s3-net

  frontend:
    image: s3-mvp-frontend
    container_name: s3-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - s3-net

networks:
  s3-net:
    driver: bridge
